[build]
publish = ".next"


[dev]
  publish = "dist"
  command = "npm run dev"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "https://mieland.com.my"
  status = 302
  conditions = { Country = ["MY"] }

  [[redirects]]
  from = "/*"
  to = "https://www.eligocs.com"
  status = 302
  conditions = { Country = ["US"] }